-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 22:06:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskforce` DEFAULT CHARACTER SET utf8 ;
USE `taskforce` ;

-- -----------------------------------------------------
-- Table `taskforce`.`cities_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`cities_list` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`cities_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `latitude` DECIMAL(8,6) NOT NULL,
  `longtide` DECIMAL(8,6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`users` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reg_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(128) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `birthday` DATE NULL,
  `about` TEXT NULL,
  `city` INT NULL,
  `role` INT NOT NULL DEFAULT 0,
  `phone` VARCHAR(45) NULL,
  `skype` VARCHAR(128) NULL,
  `telegram` VARCHAR(128) NULL,
  `is_show_profile` INT NOT NULL DEFAULT 0,
  `is_new_messages` INT NOT NULL DEFAULT 0,
  `is_new_reviews` INT NOT NULL DEFAULT 0,
  `is_new_actions` INT NOT NULL DEFAULT 0,
  `is_show_contacts` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `city_id_users_idx` (`city` ASC),
  CONSTRAINT `city_id_users`
    FOREIGN KEY (`city`)
    REFERENCES `taskforce`.`cities_list` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`task_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`task_categories` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`task_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`task_attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`task_attachments` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`task_attachments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `attachment_path` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`tasks` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(128) NOT NULL,
  `description` TEXT NULL,
  `cat_id` INT NOT NULL,
  `city_id` INT NULL,
  `price` INT NULL,
  `date_to` DATE NULL,
  `task_executor` INT NULL,
  `task_customer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cat_id_tasks_idx` (`cat_id` ASC),
  INDEX `city_id_tasks_idx` (`city_id` ASC),
  CONSTRAINT `cat_id_tasks`
    FOREIGN KEY (`cat_id`)
    REFERENCES `taskforce`.`task_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `city_id_tasks`
    FOREIGN KEY (`city_id`)
    REFERENCES `taskforce`.`cities_list` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`task_response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`task_response` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`task_response` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `executor_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `price` INT NULL,
  `comment` INT NULL,
  `task_responsecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `executor_id_response_idx` (`executor_id` ASC),
  INDEX `task_id_response_idx` (`task_id` ASC),
  CONSTRAINT `executor_id_response`
    FOREIGN KEY (`executor_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task_id_response`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`user_portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`user_portfolio` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`user_portfolio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `file_path` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id_folio`
    FOREIGN KEY (`id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`messages` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `messages` TEXT NOT NULL,
  `message_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `sender_id_message_idx` (`sender_id` ASC),
  INDEX `recipient_id_message_idx` (`recipient_id` ASC),
  INDEX `task_id_message_idx` (`task_id` ASC),
  CONSTRAINT `sender_id_message`
    FOREIGN KEY (`sender_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `recipient_id_message`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task_id_message`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskforce`.`reviews` ;

CREATE TABLE IF NOT EXISTS `taskforce`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `executor_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `mark` INT NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `executor_id_reviews_idx` (`executor_id` ASC),
  INDEX `customer_id_reviews_idx` (`customer_id` ASC),
  INDEX `task_id_reviews_idx` (`task_id` ASC),
  CONSTRAINT `executor_id_reviews`
    FOREIGN KEY (`executor_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `customer_id_reviews`
    FOREIGN KEY (`customer_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task_id_reviews`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
